--- #YAML:1.0
name:                MIME-EcoEncode
version:             0.81
abstract:            MIME Encoding (Economical)
license:             perl
author:              
    - MURATA Yasuhisa <murata@nips.ac.jp>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    MIME::Base64:                  3.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
